### ISSUE TITLE
Auto-adjust the layout to fit screen window

### ISSUE THREAD

**Issue by neelkrish** [OVVE/software-ui#1]
Tested commit: c559ff0ee6d20415d090c467ca8dd5a8614c57a2- Auto Resize works. 

Pending: We need to align the knobs to fit the layout. 
https://files.slack.com/files-pri/TVBJ9C58S-F010NAP8BSM/image_from_ios.jpg

4/17 - The screen size is fixed at 800x480.  We won't put effort into dynamic resizing at this time.

**Comment by avigupta33** [comment]
I think this should be fixed on the 3/27 15:30 commit

**Comment by avigupta33** [comment]
Are we still planning to add this functionality?

**Comment by avigupta33** [comment]
Do we still intend to support auto-adjustment for screen sizes?
