### ISSUE TITLE
UI pauses, untill button click

### ISSUE THREAD

**Issue by neelkrish** [OVVE/software-ui#19]
I see that the comms simulator is feeding simulated values to TV, PEEP, Ppeak and pplat. This simulation pauses after some time. It restarts after I click on UI. A suspended state can cause a problem to a medical assistant who is monitoring these values. 

[UI_pause.zip](https://github.com/OVVE/software-ui/files/4432786/UI_pause.zip)

**Comment by neelkrish** [comment]
message stream in console does not stop

**Comment by avigupta33** [comment]
This should be resolved. Can you check and let me know so we can close this?

**Comment by neelkrish** [comment]
Fixed in latest patch

**Comment by neelkrish** [comment]
Fixed in debug_hang branch. There are times when the UI is not displaying values from console- fast enough. Perhaps a refresh issue?
