### ISSUE TITLE
TV Insp and Exp values on UI dont populate in sync with the console o/p

### ISSUE THREAD

**Issue by neelkrish** [OVVE/software-ui#40]
**Reproducibility:** Consistent
**Steps to reproduce:**

- cd  software-ui
- git checkout deug-hang
- cd ovve_ui
- python3 ovve_ui.py

Once UI comes up, set Resp rate (11 bpm), Tidal Volume (550 ml) Click start

Compare data displayed in UI vs console. There is a mismatch.

**Comment by avigupta33** [comment]
Is this resolved now?
