### ISSUE TITLE
UI freezes for a few seconds while running. 

### ISSUE THREAD

**Issue by neelkrish** [OVVE/software-ui#42]
**Reproducibility**: Intermittent
**Steps to reproduce**:

- cd software-ui
- git checkout deug-hang
- cd ovve_ui
- python3 ovve_ui.py
- Once UI comes up, set Resp rate (11 bpm), Tidal Volume (550 ml) Click start

After ~10 mins, the UI freezes with a dialog box pop up that requests to cancel or wait. After a few sends the dialog box disappears and execution continues without interrupt.

**Comment by avigupta33** [comment]
Is this resolved now?
