### ISSUE TITLE
Start/Stop Broken

### ISSUE THREAD

**Issue by mrrosen** [OVVE/software-ui#61]
https://github.com/OVVE/software-ui/blob/375b541c252f8809296a0936bc2b0388bed595f5/ovve_ui/utils/comms_link.py#L209-L222

On the develop branch, it seems like the start/stop bit is not set correctly as per the packet specification. Based on the code, it appears the LSb is being treated as a start/stop bit when it should be the MSb. Should be able to implement this in a simpler manner:

    self.cmd_pkt['mode_value'] = (self.settings.mode & 0x7f) | ((self.settings.run_state << 7) & 0x80)

**Comment by noelpaz** [comment]
Fix is here:

https://github.com/OVVE/software-ui/pull/62

Please test and review
