### ISSUE TITLE
Serial communication not working on branch develop-startbit-fix

### ISSUE THREAD

**Issue by JonnerLynx** [OVVE/software-ui#63]
Serial communication to indicate start/stop to the Arduino behaves erratically. After pressing the start button, it takes 20-50 seconds for a packet to reach the Arduino without a watchdog timeout in order to start moving the motor. We noticed this today when attempting to set up the first functional prototype with enclosure.

The following revision is "known good", in that it starts and stops the motor instantaneously when selected through the UI (keep in mind that some manual changes were applied in order to get the start bit written in the correct location):

commit 2d5f0215dbd4e89b070aa84ad0a8e8348ceb7f8b (HEAD -> develop, origin/develop)
Merge: 3c1de9a 6828bf7
Author: BrianWoodruff <brian.e.woodruff@gmail.com>
Date:   Thu Apr 9 13:46:47 2020 -0700

    Merge pull request #45 from OVVE/develop_charlie

    Merge Charlie's UI changes

**Comment by noelpaz** [comment]
Is this still an issue? We should probably be merging develop to develop

**Comment by JonnerLynx** [comment]
This is no longer an issue. As of right now, the develop branch on the software-ui project seems to work well with the develop branch of the software-controller project.

Closing.
