### ISSUE TITLE
Tv insp, pplat ppeak Data not getting populated on UI

### ISSUE THREAD

**Issue by neelkrish** [OVVE/software-ui#71]
When I simulate the reading from sensors on the Arduino side, the above fields are not getting populated in console or ui. I am able to see tv exp, ensure respiration rate and peep fields getting populated on ui and console.

**Comment by noelpaz** [comment]
I fixed this in this branch and PR

https://github.com/OVVE/software-ui/pull/74

**Comment by noelpaz** [comment]
![image (3)](https://user-images.githubusercontent.com/9592868/80269342-2430f680-866c-11ea-9cc4-bc12df40ecc2.png)
