### ISSUE TITLE
Ventilator mode change after starting ventilation operation

### ISSUE THREAD

**Issue by neelkrish** [OVVE/software-ui#72]
Start ventilator with CMV mode, after setting all required fields.
Now change mode from CMV to SIMV, apply while ventilator is running. 
Mode I reset in console and UI. 
If the function for these modes are different, then this action would be unfavorable for the patient.  There needs to a warning message or a method to prevent the change of mode while ventilator is running.

**Comment by avigupta33** [comment]
This was discussed on Slack and I think we agreed that it's okay to be able to change the mode while the vent. is running – it can just take effect on the next breath.
