### ISSUE TITLE
Set mode button shows invalid on click "start" button

### ISSUE THREAD

**Issue by neelkrish** [OVVE/software-ui#77]
When you click the "Start" ventilator button. the display on the mode button changes to "invalid"

[
![Image from iOS (2)](https://user-images.githubusercontent.com/9873867/80410272-2919c400-887f-11ea-86d6-bef89ad977c5.jpg)
](url)

**Comment by avigupta33** [comment]
@BrianWoodruff did we fix this?

**Comment by BrianWoodruff** [comment]
I don't remember if this was an explicit fix or caused by bad sim data.  Neelima, can you verify and close?
