### ISSUE TITLE
IE Ratio Representation

### ISSUE THREAD

**Issue by mrrosen** [OVVE/software-ui#85]
Currently, the serial link passes along the UI's internal representation of IE Ration, namely an enumeration of the possible set points to the ECU. However, the Data and Command packet specification requires IE to be a fixed point number (24.8 or 8.8 depending on packet version) representing the proportion of time in inhalation. So, an IE Ratio of 1:1.5 would translate to 0x0066 (`1:1.5 -> 1 / (1 + 1.5) -> 0.4 -> 0.4 * 256 -> 102`). Since the IE Ratio is measured as well as set, its important to represent the IE ratio as a fraction rather than a fixed set of values.

Suggested formula for converting:
From I:E: `I:E -> int(I / (I + E) * 256) = n`
From Fixed Point: `n -> (256 / float(n)) - 1 = E, I = 1 if (n <= 128) else (float(n) / 256) / (1 - float(n) / 256) = I, E = 1` (note, you will probably need to round to the nearest .1 to get nice numbers due to rounding error in the fixed point number

**Comment by BrianWoodruff** [comment]
This was fixed in commit 
Merge pull request #86 from OVVE/fix_ie_ratio	ab91003	BrianWoodruff <brian.e.woodruff@gmail.com>	May 4, 2020 at 5:14 PM
